/*
 * SPDX-License-Identifier: GPL-3.0-only
 * MuseScore-Studio-CLA-applies
 *
 * MuseScore Studio
 * Music Composition & Notation
 *
 * Copyright (C) 2026 MuseScore Limited and others
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <gtest/gtest.h>

#include <cmath>
#include <vector>

#include "audiotrack/audiofilereader.h"

using namespace muse;
using namespace muse::audiotrack;

namespace {
String testFile(const char* name)
{
    return String::fromUtf8(std::string(audiotrack_tests_DATA_ROOT) + "/" + name);
}

const char* SWEEP = "data/sweep-stereo-44100.wav";
const char* TONE = "data/tone-a440-mono-44100.wav";
const char* METRONOME = "data/metronome-120bpm-48000.wav";
}

// The three files are regenerated by 音频轨/test-audio/generate-test-wav.ps1 and are
// checked in next to this test (they are small: 1.4 MB / 0.4 MB / 0.8 MB). They are the
// same bytes the manual GUI check uses, so unit-test and hand-check evidence agree.

TEST(AudioFileReaderTests, OpensWavAndReadsMetadata)
{
    AudioFileReader r;
    ASSERT_TRUE(r.open(testFile(SWEEP))) << r.errorString();

    EXPECT_EQ(r.info().sampleRate, 44100);
    EXPECT_EQ(r.info().channels, 2);
    EXPECT_EQ(r.info().frames, 44100 * 8);
    EXPECT_NEAR(r.info().duration, 8.0, 0.001);
    EXPECT_TRUE(r.info().valid);
    EXPECT_FALSE(r.info().formatName.empty());
}

TEST(AudioFileReaderTests, ReadsStereoInterleavedInOrder)
{
    AudioFileReader r;
    ASSERT_TRUE(r.open(testFile(SWEEP))) << r.errorString();

    ASSERT_TRUE(r.seekToFrame(0));

    std::vector<float> buf(1024 * 2, 0.f);
    const int64_t got = r.readFrames(buf.data(), 1024, 2);
    ASSERT_EQ(got, 1024);

    // The generator makes the right channel the exact negation of the left. Verifying
    // that proves the interleaving is decoded in the right order and the channels are
    // not swapped or duplicated.
    for (int64_t f = 0; f < got; ++f) {
        EXPECT_NEAR(buf[f * 2 + 0], -buf[f * 2 + 1], 1e-4f) << "frame " << f;
    }
}

TEST(AudioFileReaderTests, SeekIsAbsoluteAndRepeatable)
{
    AudioFileReader r;
    ASSERT_TRUE(r.open(testFile(SWEEP))) << r.errorString();

    std::vector<float> a(512 * 2), b(512 * 2);

    ASSERT_TRUE(r.seekToFrame(44100));          // 1.0 s in
    ASSERT_EQ(r.readFrames(a.data(), 512, 2), 512);

    ASSERT_TRUE(r.seekToFrame(44100));          // back to the same spot
    ASSERT_EQ(r.readFrames(b.data(), 512, 2), 512);

    EXPECT_EQ(a, b);
}

TEST(AudioFileReaderTests, MonoIsDuplicatedToStereo)
{
    AudioFileReader r;
    ASSERT_TRUE(r.open(testFile(TONE))) << r.errorString();
    ASSERT_TRUE(r.seekToFrame(0));

    std::vector<float> buf(256 * 2, 0.f);
    ASSERT_EQ(r.readFrames(buf.data(), 256, 2), 256);

    for (int64_t f = 0; f < 256; ++f) {
        EXPECT_FLOAT_EQ(buf[f * 2 + 0], buf[f * 2 + 1]) << "frame " << f;
    }
}

TEST(AudioFileReaderTests, ReadPastEndReturnsZeroNotGarbage)
{
    AudioFileReader r;
    ASSERT_TRUE(r.open(testFile(TONE))) << r.errorString();

    ASSERT_TRUE(r.seekToFrame(r.info().frames));
    std::vector<float> buf(64, 12345.f);
    EXPECT_EQ(r.readFrames(buf.data(), 64, 1), 0);
}

TEST(AudioFileReaderTests, RejectsMissingAndNonAudioFiles)
{
    AudioFileReader r;
    EXPECT_FALSE(r.open(testFile("data/does-not-exist.wav")));
    EXPECT_FALSE(r.errorString().empty());

    // A text file is not audio: this is the "user picked the wrong file" path.
    AudioFileReader r2;
    EXPECT_FALSE(r2.open(testFile("../tests/CMakeLists.txt")));
}

TEST(AudioFileReaderTests, ReadAllMatchesStreamedReads)
{
    AudioFileReader r;
    ASSERT_TRUE(r.open(testFile(METRONOME))) << r.errorString();

    std::vector<float> all;
    ASSERT_TRUE(r.readAll(all, 1));
    EXPECT_EQ(all.size(), static_cast<size_t>(r.info().frames));

    // Streaming from the start must produce identical samples.
    ASSERT_TRUE(r.seekToFrame(0));
    std::vector<float> chunk(3000);
    int64_t done = 0;
    while (done < r.info().frames) {
        const int64_t want = std::min<int64_t>(3000, r.info().frames - done);
        const int64_t got = r.readFrames(chunk.data(), want, 1);
        if (got <= 0) {
            break;
        }
        for (int64_t i = 0; i < got; ++i) {
            EXPECT_FLOAT_EQ(chunk[i], all[done + i]) << "sample " << (done + i);
        }
        done += got;
    }
    EXPECT_EQ(done, r.info().frames);
}
